import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import dns from "node:dns";

// Ensure localhost resolves to ipv4 127.0.0.1 for high compatibility
dns.setDefaultResultOrder("ipv4first");

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware to parse incoming JSON payloads
  app.use(express.json());

  // API Route: Submit contact information securely to Supabase
  app.post("/api/contact", async (req, res) => {
    try {
      const { name, email, phone, message } = req.body;

      // Validate required inputs
      if (!name || !email || !phone) {
        return res.status(400).json({ 
          success: false, 
          error: "Required fields (name, email, phone) are missing." 
        });
      }

      const supabaseUrl = process.env.SUPABASE_URL || "https://zgghgoevublzuaemxguv.supabase.co";
      const supabaseKey = process.env.SUPABASE_ANON_KEY || "sb_publishable_kSCYAAvIi7TRKRYA6gGyHQ_DZuYW_Yf";

      // POST to Supabase REST endpoint to insert standard table row
      const targetUrl = `${supabaseUrl}/rest/v1/contact`;

      const response = await fetch(targetUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "apikey": supabaseKey,
          "Authorization": `Bearer ${supabaseKey}`,
          "Prefer": "return=representation"
        },
        body: JSON.stringify({
          name,
          email,
          phone,
          message,
          created_at: new Date().toISOString()
        })
      });

      if (!response.ok) {
        const textError = await response.text();
        console.error("Supabase request failed:", textError);
        
        // Handle common situation where the 'contact' table is not yet created in their Supabase project
        if (
          textError.includes(`"42P01"`) || 
          textError.includes(`"PGRST205"`) ||
          textError.toLowerCase().includes("relation") || 
          textError.toLowerCase().includes("does not exist") ||
          textError.toLowerCase().includes("could not find the table")
        ) {
          return res.status(422).json({
            success: false,
            error: "table_missing",
            message: "Table 'contact' does not exist in your Supabase project schema cache yet.",
            instructions: "-- 1. Run this script in the Supabase SQL Editor to create the 'contact' table:\nCREATE TABLE contact (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,\n  name TEXT NOT NULL,\n  email TEXT NOT NULL,\n  phone TEXT,\n  message TEXT\n);\n\n-- 2. Disable RLS to allow public form submissions or add a public insert policy:\nALTER TABLE contact DISABLE ROW LEVEL SECURITY;"
          });
        }

        // Handle Row-Level Security (RLS) policy errors
        if (textError.includes(`"42501"`) || textError.toLowerCase().includes("row-level security") || textError.toLowerCase().includes("violates")) {
          return res.status(422).json({
            success: false,
            error: "rls_violation",
            message: "Row-Level Security (RLS) is active on your 'contact' table, but there is no policy that allows public inserts.",
            instructions: "-- Run this script in your Supabase SQL Editor to allow public form submissions:\n\nCREATE POLICY \"Enable insert for all users\" ON public.contact\nFOR INSERT \nWITH CHECK (true);\n\n-- Alternative: Completely disable RLS of the 'contact' table:\n-- ALTER TABLE contact DISABLE ROW LEVEL SECURITY;"
          });
        }

        return res.status(response.status).json({
          success: false,
          error: `Supabase returned status code ${response.status}`,
          details: textError
        });
      }

      // Success payload
      const data = await response.json();
      return res.status(200).json({
        success: true,
        data
      });

    } catch (error: any) {
      console.error("Internal Server Error in /api/contact:", error);
      return res.status(500).json({
        success: false,
        error: "Internal server error occurred.",
        message: error?.message || String(error)
      });
    }
  });

  // Health endpoint
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // Vite middleware setup for HMR, dev asset loading, and production SPA static bundling
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { 
        middlewareMode: true,
        hmr: false // HMR is disabled in this environment
      },
      appType: "spa"
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
